/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as PublicRouteImport } from './pages/_public'
import { Route as AuthenticatedRouteImport } from './pages/_authenticated'
import { Route as PublicIndexRouteImport } from './pages/_public/index'
import { Route as SettingsProfileRouteImport } from './pages/settings/profile'
import { Route as AuthenticatedLearnerRouteImport } from './pages/_authenticated._learner'
import { Route as AuthenticatedFacultyRouteImport } from './pages/_authenticated._faculty'
import { Route as AuthenticatedAdminRouteImport } from './pages/_authenticated._admin'
import { Route as PublicCoursesCourseIdRouteImport } from './pages/_public/courses/$courseId'
import { Route as AuthenticatedLearnerLearnIndexRouteImport } from './pages/_authenticated._learner/learn/index'
import { Route as AuthenticatedAdminAIndexRouteImport } from './pages/_authenticated._admin.a/index'
import { Route as AuthenticatedLearnerLearnLibraryRouteImport } from './pages/_authenticated._learner/learn/library'
import { Route as AuthenticatedLearnerLearnCoursesRouteImport } from './pages/_authenticated._learner/learn/courses'
import { Route as AuthenticatedFacultyFDashboardRouteImport } from './pages/_authenticated._faculty.f/dashboard'
import { Route as AuthenticatedAdminAContentApprovalRouteImport } from './pages/_authenticated._admin.a/content-approval'
import { Route as AuthenticatedAdminACoursesIndexRouteImport } from './pages/_authenticated._admin.a/courses.index'
import { Route as AuthenticatedAdminACoursesCourseIdRouteImport } from './pages/_authenticated._admin.a/courses.$courseId'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLearnerRoute = AuthenticatedLearnerRouteImport.update({
  id: '/_learner',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFacultyRoute = AuthenticatedFacultyRouteImport.update({
  id: '/_faculty',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const PublicCoursesCourseIdRoute = PublicCoursesCourseIdRouteImport.update({
  id: '/courses/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => PublicRoute,
} as any)
const AuthenticatedLearnerLearnIndexRoute =
  AuthenticatedLearnerLearnIndexRouteImport.update({
    id: '/learn/',
    path: '/learn/',
    getParentRoute: () => AuthenticatedLearnerRoute,
  } as any)
const AuthenticatedAdminAIndexRoute =
  AuthenticatedAdminAIndexRouteImport.update({
    id: '/a/',
    path: '/a/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedLearnerLearnLibraryRoute =
  AuthenticatedLearnerLearnLibraryRouteImport.update({
    id: '/learn/library',
    path: '/learn/library',
    getParentRoute: () => AuthenticatedLearnerRoute,
  } as any)
const AuthenticatedLearnerLearnCoursesRoute =
  AuthenticatedLearnerLearnCoursesRouteImport.update({
    id: '/learn/courses',
    path: '/learn/courses',
    getParentRoute: () => AuthenticatedLearnerRoute,
  } as any)
const AuthenticatedFacultyFDashboardRoute =
  AuthenticatedFacultyFDashboardRouteImport.update({
    id: '/f/dashboard',
    path: '/f/dashboard',
    getParentRoute: () => AuthenticatedFacultyRoute,
  } as any)
const AuthenticatedAdminAContentApprovalRoute =
  AuthenticatedAdminAContentApprovalRouteImport.update({
    id: '/a/content-approval',
    path: '/a/content-approval',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminACoursesIndexRoute =
  AuthenticatedAdminACoursesIndexRouteImport.update({
    id: '/a/courses/',
    path: '/a/courses/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminACoursesCourseIdRoute =
  AuthenticatedAdminACoursesCourseIdRouteImport.update({
    id: '/a/courses/$courseId',
    path: '/a/courses/$courseId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/settings/profile': typeof SettingsProfileRoute
  '/': typeof PublicIndexRoute
  '/courses/$courseId': typeof PublicCoursesCourseIdRoute
  '/a/content-approval': typeof AuthenticatedAdminAContentApprovalRoute
  '/f/dashboard': typeof AuthenticatedFacultyFDashboardRoute
  '/learn/courses': typeof AuthenticatedLearnerLearnCoursesRoute
  '/learn/library': typeof AuthenticatedLearnerLearnLibraryRoute
  '/a': typeof AuthenticatedAdminAIndexRoute
  '/learn': typeof AuthenticatedLearnerLearnIndexRoute
  '/a/courses/$courseId': typeof AuthenticatedAdminACoursesCourseIdRoute
  '/a/courses': typeof AuthenticatedAdminACoursesIndexRoute
}
export interface FileRoutesByTo {
  '/settings/profile': typeof SettingsProfileRoute
  '/': typeof PublicIndexRoute
  '/courses/$courseId': typeof PublicCoursesCourseIdRoute
  '/a/content-approval': typeof AuthenticatedAdminAContentApprovalRoute
  '/f/dashboard': typeof AuthenticatedFacultyFDashboardRoute
  '/learn/courses': typeof AuthenticatedLearnerLearnCoursesRoute
  '/learn/library': typeof AuthenticatedLearnerLearnLibraryRoute
  '/a': typeof AuthenticatedAdminAIndexRoute
  '/learn': typeof AuthenticatedLearnerLearnIndexRoute
  '/a/courses/$courseId': typeof AuthenticatedAdminACoursesCourseIdRoute
  '/a/courses': typeof AuthenticatedAdminACoursesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/_faculty': typeof AuthenticatedFacultyRouteWithChildren
  '/_authenticated/_learner': typeof AuthenticatedLearnerRouteWithChildren
  '/settings/profile': typeof SettingsProfileRoute
  '/_public/': typeof PublicIndexRoute
  '/_public/courses/$courseId': typeof PublicCoursesCourseIdRoute
  '/_authenticated/_admin/a/content-approval': typeof AuthenticatedAdminAContentApprovalRoute
  '/_authenticated/_faculty/f/dashboard': typeof AuthenticatedFacultyFDashboardRoute
  '/_authenticated/_learner/learn/courses': typeof AuthenticatedLearnerLearnCoursesRoute
  '/_authenticated/_learner/learn/library': typeof AuthenticatedLearnerLearnLibraryRoute
  '/_authenticated/_admin/a/': typeof AuthenticatedAdminAIndexRoute
  '/_authenticated/_learner/learn/': typeof AuthenticatedLearnerLearnIndexRoute
  '/_authenticated/_admin/a/courses/$courseId': typeof AuthenticatedAdminACoursesCourseIdRoute
  '/_authenticated/_admin/a/courses/': typeof AuthenticatedAdminACoursesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/settings/profile'
    | '/'
    | '/courses/$courseId'
    | '/a/content-approval'
    | '/f/dashboard'
    | '/learn/courses'
    | '/learn/library'
    | '/a'
    | '/learn'
    | '/a/courses/$courseId'
    | '/a/courses'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/settings/profile'
    | '/'
    | '/courses/$courseId'
    | '/a/content-approval'
    | '/f/dashboard'
    | '/learn/courses'
    | '/learn/library'
    | '/a'
    | '/learn'
    | '/a/courses/$courseId'
    | '/a/courses'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_public'
    | '/_authenticated/_admin'
    | '/_authenticated/_faculty'
    | '/_authenticated/_learner'
    | '/settings/profile'
    | '/_public/'
    | '/_public/courses/$courseId'
    | '/_authenticated/_admin/a/content-approval'
    | '/_authenticated/_faculty/f/dashboard'
    | '/_authenticated/_learner/learn/courses'
    | '/_authenticated/_learner/learn/library'
    | '/_authenticated/_admin/a/'
    | '/_authenticated/_learner/learn/'
    | '/_authenticated/_admin/a/courses/$courseId'
    | '/_authenticated/_admin/a/courses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  SettingsProfileRoute: typeof SettingsProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_learner': {
      id: '/_authenticated/_learner'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedLearnerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_faculty': {
      id: '/_authenticated/_faculty'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedFacultyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_public/courses/$courseId': {
      id: '/_public/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof PublicCoursesCourseIdRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authenticated/_learner/learn/': {
      id: '/_authenticated/_learner/learn/'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof AuthenticatedLearnerLearnIndexRouteImport
      parentRoute: typeof AuthenticatedLearnerRoute
    }
    '/_authenticated/_admin/a/': {
      id: '/_authenticated/_admin/a/'
      path: '/a'
      fullPath: '/a'
      preLoaderRoute: typeof AuthenticatedAdminAIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_learner/learn/library': {
      id: '/_authenticated/_learner/learn/library'
      path: '/learn/library'
      fullPath: '/learn/library'
      preLoaderRoute: typeof AuthenticatedLearnerLearnLibraryRouteImport
      parentRoute: typeof AuthenticatedLearnerRoute
    }
    '/_authenticated/_learner/learn/courses': {
      id: '/_authenticated/_learner/learn/courses'
      path: '/learn/courses'
      fullPath: '/learn/courses'
      preLoaderRoute: typeof AuthenticatedLearnerLearnCoursesRouteImport
      parentRoute: typeof AuthenticatedLearnerRoute
    }
    '/_authenticated/_faculty/f/dashboard': {
      id: '/_authenticated/_faculty/f/dashboard'
      path: '/f/dashboard'
      fullPath: '/f/dashboard'
      preLoaderRoute: typeof AuthenticatedFacultyFDashboardRouteImport
      parentRoute: typeof AuthenticatedFacultyRoute
    }
    '/_authenticated/_admin/a/content-approval': {
      id: '/_authenticated/_admin/a/content-approval'
      path: '/a/content-approval'
      fullPath: '/a/content-approval'
      preLoaderRoute: typeof AuthenticatedAdminAContentApprovalRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/a/courses/': {
      id: '/_authenticated/_admin/a/courses/'
      path: '/a/courses'
      fullPath: '/a/courses'
      preLoaderRoute: typeof AuthenticatedAdminACoursesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/a/courses/$courseId': {
      id: '/_authenticated/_admin/a/courses/$courseId'
      path: '/a/courses/$courseId'
      fullPath: '/a/courses/$courseId'
      preLoaderRoute: typeof AuthenticatedAdminACoursesCourseIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAContentApprovalRoute: typeof AuthenticatedAdminAContentApprovalRoute
  AuthenticatedAdminAIndexRoute: typeof AuthenticatedAdminAIndexRoute
  AuthenticatedAdminACoursesCourseIdRoute: typeof AuthenticatedAdminACoursesCourseIdRoute
  AuthenticatedAdminACoursesIndexRoute: typeof AuthenticatedAdminACoursesIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAContentApprovalRoute:
    AuthenticatedAdminAContentApprovalRoute,
  AuthenticatedAdminAIndexRoute: AuthenticatedAdminAIndexRoute,
  AuthenticatedAdminACoursesCourseIdRoute:
    AuthenticatedAdminACoursesCourseIdRoute,
  AuthenticatedAdminACoursesIndexRoute: AuthenticatedAdminACoursesIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedFacultyRouteChildren {
  AuthenticatedFacultyFDashboardRoute: typeof AuthenticatedFacultyFDashboardRoute
}

const AuthenticatedFacultyRouteChildren: AuthenticatedFacultyRouteChildren = {
  AuthenticatedFacultyFDashboardRoute: AuthenticatedFacultyFDashboardRoute,
}

const AuthenticatedFacultyRouteWithChildren =
  AuthenticatedFacultyRoute._addFileChildren(AuthenticatedFacultyRouteChildren)

interface AuthenticatedLearnerRouteChildren {
  AuthenticatedLearnerLearnCoursesRoute: typeof AuthenticatedLearnerLearnCoursesRoute
  AuthenticatedLearnerLearnLibraryRoute: typeof AuthenticatedLearnerLearnLibraryRoute
  AuthenticatedLearnerLearnIndexRoute: typeof AuthenticatedLearnerLearnIndexRoute
}

const AuthenticatedLearnerRouteChildren: AuthenticatedLearnerRouteChildren = {
  AuthenticatedLearnerLearnCoursesRoute: AuthenticatedLearnerLearnCoursesRoute,
  AuthenticatedLearnerLearnLibraryRoute: AuthenticatedLearnerLearnLibraryRoute,
  AuthenticatedLearnerLearnIndexRoute: AuthenticatedLearnerLearnIndexRoute,
}

const AuthenticatedLearnerRouteWithChildren =
  AuthenticatedLearnerRoute._addFileChildren(AuthenticatedLearnerRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedFacultyRoute: typeof AuthenticatedFacultyRouteWithChildren
  AuthenticatedLearnerRoute: typeof AuthenticatedLearnerRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedFacultyRoute: AuthenticatedFacultyRouteWithChildren,
  AuthenticatedLearnerRoute: AuthenticatedLearnerRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PublicRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
  PublicCoursesCourseIdRoute: typeof PublicCoursesCourseIdRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
  PublicCoursesCourseIdRoute: PublicCoursesCourseIdRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  SettingsProfileRoute: SettingsProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
