/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as PublicRouteImport } from './pages/_public'
import { Route as AuthenticatedRouteImport } from './pages/_authenticated'
import { Route as PublicIndexRouteImport } from './pages/_public/index'
import { Route as PublicFaqRouteImport } from './pages/_public/faq'
import { Route as PublicContactRouteImport } from './pages/_public/contact'
import { Route as PublicAboutRouteImport } from './pages/_public/about'
import { Route as PublicCoursesIndexRouteImport } from './pages/_public/courses.index'
import { Route as PublicStaffLoginRouteImport } from './pages/_public/staff.login'
import { Route as PublicCoursesCourseIdRouteImport } from './pages/_public/courses.$courseId'
import { Route as AuthenticatedCCoursesRouteImport } from './pages/_authenticated.c/courses'
import { Route as AuthenticatedCCourseIdRouteImport } from './pages/_authenticated.c/$courseId'
import { Route as AuthenticatedAdminARouteImport } from './pages/_authenticated._admin.a'
import { Route as AuthenticatedCCourseIdIndexRouteImport } from './pages/_authenticated.c/$courseId.index'
import { Route as AuthenticatedAdminAIndexRouteImport } from './pages/_authenticated._admin.a/index'
import { Route as AuthenticatedAdminAUsersRouteImport } from './pages/_authenticated._admin.a/users'
import { Route as AuthenticatedAdminACoursesRouteImport } from './pages/_authenticated._admin.a/courses'
import { Route as AuthenticatedAdminAContentApprovalsRouteImport } from './pages/_authenticated._admin.a/content-approvals'
import { Route as AuthenticatedAdminAUsersIndexRouteImport } from './pages/_authenticated._admin.a/users/index'
import { Route as AuthenticatedAdminACoursesIndexRouteImport } from './pages/_authenticated._admin.a/courses/index'
import { Route as AuthenticatedAdminAContentIndexRouteImport } from './pages/_authenticated._admin.a/content/index'
import { Route as AuthenticatedAdminAContentApprovalsIndexRouteImport } from './pages/_authenticated._admin.a/content-approvals/index'
import { Route as AuthenticatedAdminACategoriesIndexRouteImport } from './pages/_authenticated._admin.a/categories/index'
import { Route as AuthenticatedAdminAAnalyticsIndexRouteImport } from './pages/_authenticated._admin.a/analytics/index'
import { Route as AuthenticatedAdminAUsersCreateRouteImport } from './pages/_authenticated._admin.a/users/create'
import { Route as AuthenticatedAdminAUsersUserIdRouteImport } from './pages/_authenticated._admin.a/users/$userId'
import { Route as AuthenticatedAdminACoursesNewRouteImport } from './pages/_authenticated._admin.a/courses/new'
import { Route as AuthenticatedAdminACoursesCourseIdRouteImport } from './pages/_authenticated._admin.a/courses/$courseId'
import { Route as AuthenticatedAdminACategoriesOrganizeRouteImport } from './pages/_authenticated._admin.a/categories/organize'
import { Route as AuthenticatedAdminACategoriesNewRouteImport } from './pages/_authenticated._admin.a/categories/new'
import { Route as AuthenticatedAdminAAnalyticsReportsRouteImport } from './pages/_authenticated._admin.a/analytics/reports'
import { Route as AuthenticatedAdminAAnalyticsEnrollmentsRouteImport } from './pages/_authenticated._admin.a/analytics/enrollments'
import { Route as AuthenticatedAdminAAnalyticsCoursesRouteImport } from './pages/_authenticated._admin.a/analytics/courses'
import { Route as AuthenticatedCCourseIdMModuleIdIndexRouteImport } from './pages/_authenticated.c/$courseId.m.$moduleId.index'
import { Route as AuthenticatedAdminAContentContentTypeContentIdRouteImport } from './pages/_authenticated._admin.a/content/$contentType.$contentId'
import { Route as AuthenticatedCCourseIdMModuleIdLessonsLessonIdRouteImport } from './pages/_authenticated.c/$courseId.m.$moduleId.lessons.$lessonId'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicFaqRoute = PublicFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => PublicRoute,
} as any)
const PublicContactRoute = PublicContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCoursesIndexRoute = PublicCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicStaffLoginRoute = PublicStaffLoginRouteImport.update({
  id: '/staff/login',
  path: '/staff/login',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCoursesCourseIdRoute = PublicCoursesCourseIdRouteImport.update({
  id: '/courses/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => PublicRoute,
} as any)
const AuthenticatedCCoursesRoute = AuthenticatedCCoursesRouteImport.update({
  id: '/c/courses',
  path: '/c/courses',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCCourseIdRoute = AuthenticatedCCourseIdRouteImport.update({
  id: '/c/$courseId',
  path: '/c/$courseId',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminARoute = AuthenticatedAdminARouteImport.update({
  id: '/_admin/a',
  path: '/a',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCCourseIdIndexRoute =
  AuthenticatedCCourseIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCCourseIdRoute,
  } as any)
const AuthenticatedAdminAIndexRoute =
  AuthenticatedAdminAIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminARoute,
  } as any)
const AuthenticatedAdminAUsersRoute =
  AuthenticatedAdminAUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedAdminARoute,
  } as any)
const AuthenticatedAdminACoursesRoute =
  AuthenticatedAdminACoursesRouteImport.update({
    id: '/courses',
    path: '/courses',
    getParentRoute: () => AuthenticatedAdminARoute,
  } as any)
const AuthenticatedAdminAContentApprovalsRoute =
  AuthenticatedAdminAContentApprovalsRouteImport.update({
    id: '/content-approvals',
    path: '/content-approvals',
    getParentRoute: () => AuthenticatedAdminARoute,
  } as any)
const AuthenticatedAdminAUsersIndexRoute =
  AuthenticatedAdminAUsersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminAUsersRoute,
  } as any)
const AuthenticatedAdminACoursesIndexRoute =
  AuthenticatedAdminACoursesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminACoursesRoute,
  } as any)
const AuthenticatedAdminAContentIndexRoute =
  AuthenticatedAdminAContentIndexRouteImport.update({
    id: '/content/',
    path: '/content/',
    getParentRoute: () => AuthenticatedAdminARoute,
  } as any)
const AuthenticatedAdminAContentApprovalsIndexRoute =
  AuthenticatedAdminAContentApprovalsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminAContentApprovalsRoute,
  } as any)
const AuthenticatedAdminACategoriesIndexRoute =
  AuthenticatedAdminACategoriesIndexRouteImport.update({
    id: '/categories/',
    path: '/categories/',
    getParentRoute: () => AuthenticatedAdminARoute,
  } as any)
const AuthenticatedAdminAAnalyticsIndexRoute =
  AuthenticatedAdminAAnalyticsIndexRouteImport.update({
    id: '/analytics/',
    path: '/analytics/',
    getParentRoute: () => AuthenticatedAdminARoute,
  } as any)
const AuthenticatedAdminAUsersCreateRoute =
  AuthenticatedAdminAUsersCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthenticatedAdminAUsersRoute,
  } as any)
const AuthenticatedAdminAUsersUserIdRoute =
  AuthenticatedAdminAUsersUserIdRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => AuthenticatedAdminAUsersRoute,
  } as any)
const AuthenticatedAdminACoursesNewRoute =
  AuthenticatedAdminACoursesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAdminACoursesRoute,
  } as any)
const AuthenticatedAdminACoursesCourseIdRoute =
  AuthenticatedAdminACoursesCourseIdRouteImport.update({
    id: '/$courseId',
    path: '/$courseId',
    getParentRoute: () => AuthenticatedAdminACoursesRoute,
  } as any)
const AuthenticatedAdminACategoriesOrganizeRoute =
  AuthenticatedAdminACategoriesOrganizeRouteImport.update({
    id: '/categories/organize',
    path: '/categories/organize',
    getParentRoute: () => AuthenticatedAdminARoute,
  } as any)
const AuthenticatedAdminACategoriesNewRoute =
  AuthenticatedAdminACategoriesNewRouteImport.update({
    id: '/categories/new',
    path: '/categories/new',
    getParentRoute: () => AuthenticatedAdminARoute,
  } as any)
const AuthenticatedAdminAAnalyticsReportsRoute =
  AuthenticatedAdminAAnalyticsReportsRouteImport.update({
    id: '/analytics/reports',
    path: '/analytics/reports',
    getParentRoute: () => AuthenticatedAdminARoute,
  } as any)
const AuthenticatedAdminAAnalyticsEnrollmentsRoute =
  AuthenticatedAdminAAnalyticsEnrollmentsRouteImport.update({
    id: '/analytics/enrollments',
    path: '/analytics/enrollments',
    getParentRoute: () => AuthenticatedAdminARoute,
  } as any)
const AuthenticatedAdminAAnalyticsCoursesRoute =
  AuthenticatedAdminAAnalyticsCoursesRouteImport.update({
    id: '/analytics/courses',
    path: '/analytics/courses',
    getParentRoute: () => AuthenticatedAdminARoute,
  } as any)
const AuthenticatedCCourseIdMModuleIdIndexRoute =
  AuthenticatedCCourseIdMModuleIdIndexRouteImport.update({
    id: '/m/$moduleId/',
    path: '/m/$moduleId/',
    getParentRoute: () => AuthenticatedCCourseIdRoute,
  } as any)
const AuthenticatedAdminAContentContentTypeContentIdRoute =
  AuthenticatedAdminAContentContentTypeContentIdRouteImport.update({
    id: '/content/$contentType/$contentId',
    path: '/content/$contentType/$contentId',
    getParentRoute: () => AuthenticatedAdminARoute,
  } as any)
const AuthenticatedCCourseIdMModuleIdLessonsLessonIdRoute =
  AuthenticatedCCourseIdMModuleIdLessonsLessonIdRouteImport.update({
    id: '/m/$moduleId/lessons/$lessonId',
    path: '/m/$moduleId/lessons/$lessonId',
    getParentRoute: () => AuthenticatedCCourseIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/about': typeof PublicAboutRoute
  '/contact': typeof PublicContactRoute
  '/faq': typeof PublicFaqRoute
  '/': typeof PublicIndexRoute
  '/a': typeof AuthenticatedAdminARouteWithChildren
  '/c/$courseId': typeof AuthenticatedCCourseIdRouteWithChildren
  '/c/courses': typeof AuthenticatedCCoursesRoute
  '/courses/$courseId': typeof PublicCoursesCourseIdRoute
  '/staff/login': typeof PublicStaffLoginRoute
  '/courses': typeof PublicCoursesIndexRoute
  '/a/content-approvals': typeof AuthenticatedAdminAContentApprovalsRouteWithChildren
  '/a/courses': typeof AuthenticatedAdminACoursesRouteWithChildren
  '/a/users': typeof AuthenticatedAdminAUsersRouteWithChildren
  '/a/': typeof AuthenticatedAdminAIndexRoute
  '/c/$courseId/': typeof AuthenticatedCCourseIdIndexRoute
  '/a/analytics/courses': typeof AuthenticatedAdminAAnalyticsCoursesRoute
  '/a/analytics/enrollments': typeof AuthenticatedAdminAAnalyticsEnrollmentsRoute
  '/a/analytics/reports': typeof AuthenticatedAdminAAnalyticsReportsRoute
  '/a/categories/new': typeof AuthenticatedAdminACategoriesNewRoute
  '/a/categories/organize': typeof AuthenticatedAdminACategoriesOrganizeRoute
  '/a/courses/$courseId': typeof AuthenticatedAdminACoursesCourseIdRoute
  '/a/courses/new': typeof AuthenticatedAdminACoursesNewRoute
  '/a/users/$userId': typeof AuthenticatedAdminAUsersUserIdRoute
  '/a/users/create': typeof AuthenticatedAdminAUsersCreateRoute
  '/a/analytics': typeof AuthenticatedAdminAAnalyticsIndexRoute
  '/a/categories': typeof AuthenticatedAdminACategoriesIndexRoute
  '/a/content-approvals/': typeof AuthenticatedAdminAContentApprovalsIndexRoute
  '/a/content': typeof AuthenticatedAdminAContentIndexRoute
  '/a/courses/': typeof AuthenticatedAdminACoursesIndexRoute
  '/a/users/': typeof AuthenticatedAdminAUsersIndexRoute
  '/a/content/$contentType/$contentId': typeof AuthenticatedAdminAContentContentTypeContentIdRoute
  '/c/$courseId/m/$moduleId': typeof AuthenticatedCCourseIdMModuleIdIndexRoute
  '/c/$courseId/m/$moduleId/lessons/$lessonId': typeof AuthenticatedCCourseIdMModuleIdLessonsLessonIdRoute
}
export interface FileRoutesByTo {
  '/about': typeof PublicAboutRoute
  '/contact': typeof PublicContactRoute
  '/faq': typeof PublicFaqRoute
  '/': typeof PublicIndexRoute
  '/c/courses': typeof AuthenticatedCCoursesRoute
  '/courses/$courseId': typeof PublicCoursesCourseIdRoute
  '/staff/login': typeof PublicStaffLoginRoute
  '/courses': typeof PublicCoursesIndexRoute
  '/a': typeof AuthenticatedAdminAIndexRoute
  '/c/$courseId': typeof AuthenticatedCCourseIdIndexRoute
  '/a/analytics/courses': typeof AuthenticatedAdminAAnalyticsCoursesRoute
  '/a/analytics/enrollments': typeof AuthenticatedAdminAAnalyticsEnrollmentsRoute
  '/a/analytics/reports': typeof AuthenticatedAdminAAnalyticsReportsRoute
  '/a/categories/new': typeof AuthenticatedAdminACategoriesNewRoute
  '/a/categories/organize': typeof AuthenticatedAdminACategoriesOrganizeRoute
  '/a/courses/$courseId': typeof AuthenticatedAdminACoursesCourseIdRoute
  '/a/courses/new': typeof AuthenticatedAdminACoursesNewRoute
  '/a/users/$userId': typeof AuthenticatedAdminAUsersUserIdRoute
  '/a/users/create': typeof AuthenticatedAdminAUsersCreateRoute
  '/a/analytics': typeof AuthenticatedAdminAAnalyticsIndexRoute
  '/a/categories': typeof AuthenticatedAdminACategoriesIndexRoute
  '/a/content-approvals': typeof AuthenticatedAdminAContentApprovalsIndexRoute
  '/a/content': typeof AuthenticatedAdminAContentIndexRoute
  '/a/courses': typeof AuthenticatedAdminACoursesIndexRoute
  '/a/users': typeof AuthenticatedAdminAUsersIndexRoute
  '/a/content/$contentType/$contentId': typeof AuthenticatedAdminAContentContentTypeContentIdRoute
  '/c/$courseId/m/$moduleId': typeof AuthenticatedCCourseIdMModuleIdIndexRoute
  '/c/$courseId/m/$moduleId/lessons/$lessonId': typeof AuthenticatedCCourseIdMModuleIdLessonsLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_public/about': typeof PublicAboutRoute
  '/_public/contact': typeof PublicContactRoute
  '/_public/faq': typeof PublicFaqRoute
  '/_public/': typeof PublicIndexRoute
  '/_authenticated/_admin/a': typeof AuthenticatedAdminARouteWithChildren
  '/_authenticated/c/$courseId': typeof AuthenticatedCCourseIdRouteWithChildren
  '/_authenticated/c/courses': typeof AuthenticatedCCoursesRoute
  '/_public/courses/$courseId': typeof PublicCoursesCourseIdRoute
  '/_public/staff/login': typeof PublicStaffLoginRoute
  '/_public/courses/': typeof PublicCoursesIndexRoute
  '/_authenticated/_admin/a/content-approvals': typeof AuthenticatedAdminAContentApprovalsRouteWithChildren
  '/_authenticated/_admin/a/courses': typeof AuthenticatedAdminACoursesRouteWithChildren
  '/_authenticated/_admin/a/users': typeof AuthenticatedAdminAUsersRouteWithChildren
  '/_authenticated/_admin/a/': typeof AuthenticatedAdminAIndexRoute
  '/_authenticated/c/$courseId/': typeof AuthenticatedCCourseIdIndexRoute
  '/_authenticated/_admin/a/analytics/courses': typeof AuthenticatedAdminAAnalyticsCoursesRoute
  '/_authenticated/_admin/a/analytics/enrollments': typeof AuthenticatedAdminAAnalyticsEnrollmentsRoute
  '/_authenticated/_admin/a/analytics/reports': typeof AuthenticatedAdminAAnalyticsReportsRoute
  '/_authenticated/_admin/a/categories/new': typeof AuthenticatedAdminACategoriesNewRoute
  '/_authenticated/_admin/a/categories/organize': typeof AuthenticatedAdminACategoriesOrganizeRoute
  '/_authenticated/_admin/a/courses/$courseId': typeof AuthenticatedAdminACoursesCourseIdRoute
  '/_authenticated/_admin/a/courses/new': typeof AuthenticatedAdminACoursesNewRoute
  '/_authenticated/_admin/a/users/$userId': typeof AuthenticatedAdminAUsersUserIdRoute
  '/_authenticated/_admin/a/users/create': typeof AuthenticatedAdminAUsersCreateRoute
  '/_authenticated/_admin/a/analytics/': typeof AuthenticatedAdminAAnalyticsIndexRoute
  '/_authenticated/_admin/a/categories/': typeof AuthenticatedAdminACategoriesIndexRoute
  '/_authenticated/_admin/a/content-approvals/': typeof AuthenticatedAdminAContentApprovalsIndexRoute
  '/_authenticated/_admin/a/content/': typeof AuthenticatedAdminAContentIndexRoute
  '/_authenticated/_admin/a/courses/': typeof AuthenticatedAdminACoursesIndexRoute
  '/_authenticated/_admin/a/users/': typeof AuthenticatedAdminAUsersIndexRoute
  '/_authenticated/_admin/a/content/$contentType/$contentId': typeof AuthenticatedAdminAContentContentTypeContentIdRoute
  '/_authenticated/c/$courseId/m/$moduleId/': typeof AuthenticatedCCourseIdMModuleIdIndexRoute
  '/_authenticated/c/$courseId/m/$moduleId/lessons/$lessonId': typeof AuthenticatedCCourseIdMModuleIdLessonsLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/about'
    | '/contact'
    | '/faq'
    | '/'
    | '/a'
    | '/c/$courseId'
    | '/c/courses'
    | '/courses/$courseId'
    | '/staff/login'
    | '/courses'
    | '/a/content-approvals'
    | '/a/courses'
    | '/a/users'
    | '/a/'
    | '/c/$courseId/'
    | '/a/analytics/courses'
    | '/a/analytics/enrollments'
    | '/a/analytics/reports'
    | '/a/categories/new'
    | '/a/categories/organize'
    | '/a/courses/$courseId'
    | '/a/courses/new'
    | '/a/users/$userId'
    | '/a/users/create'
    | '/a/analytics'
    | '/a/categories'
    | '/a/content-approvals/'
    | '/a/content'
    | '/a/courses/'
    | '/a/users/'
    | '/a/content/$contentType/$contentId'
    | '/c/$courseId/m/$moduleId'
    | '/c/$courseId/m/$moduleId/lessons/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/contact'
    | '/faq'
    | '/'
    | '/c/courses'
    | '/courses/$courseId'
    | '/staff/login'
    | '/courses'
    | '/a'
    | '/c/$courseId'
    | '/a/analytics/courses'
    | '/a/analytics/enrollments'
    | '/a/analytics/reports'
    | '/a/categories/new'
    | '/a/categories/organize'
    | '/a/courses/$courseId'
    | '/a/courses/new'
    | '/a/users/$userId'
    | '/a/users/create'
    | '/a/analytics'
    | '/a/categories'
    | '/a/content-approvals'
    | '/a/content'
    | '/a/courses'
    | '/a/users'
    | '/a/content/$contentType/$contentId'
    | '/c/$courseId/m/$moduleId'
    | '/c/$courseId/m/$moduleId/lessons/$lessonId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_public'
    | '/_public/about'
    | '/_public/contact'
    | '/_public/faq'
    | '/_public/'
    | '/_authenticated/_admin/a'
    | '/_authenticated/c/$courseId'
    | '/_authenticated/c/courses'
    | '/_public/courses/$courseId'
    | '/_public/staff/login'
    | '/_public/courses/'
    | '/_authenticated/_admin/a/content-approvals'
    | '/_authenticated/_admin/a/courses'
    | '/_authenticated/_admin/a/users'
    | '/_authenticated/_admin/a/'
    | '/_authenticated/c/$courseId/'
    | '/_authenticated/_admin/a/analytics/courses'
    | '/_authenticated/_admin/a/analytics/enrollments'
    | '/_authenticated/_admin/a/analytics/reports'
    | '/_authenticated/_admin/a/categories/new'
    | '/_authenticated/_admin/a/categories/organize'
    | '/_authenticated/_admin/a/courses/$courseId'
    | '/_authenticated/_admin/a/courses/new'
    | '/_authenticated/_admin/a/users/$userId'
    | '/_authenticated/_admin/a/users/create'
    | '/_authenticated/_admin/a/analytics/'
    | '/_authenticated/_admin/a/categories/'
    | '/_authenticated/_admin/a/content-approvals/'
    | '/_authenticated/_admin/a/content/'
    | '/_authenticated/_admin/a/courses/'
    | '/_authenticated/_admin/a/users/'
    | '/_authenticated/_admin/a/content/$contentType/$contentId'
    | '/_authenticated/c/$courseId/m/$moduleId/'
    | '/_authenticated/c/$courseId/m/$moduleId/lessons/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/faq': {
      id: '/_public/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof PublicFaqRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/contact': {
      id: '/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/courses/': {
      id: '/_public/courses/'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof PublicCoursesIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/staff/login': {
      id: '/_public/staff/login'
      path: '/staff/login'
      fullPath: '/staff/login'
      preLoaderRoute: typeof PublicStaffLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/courses/$courseId': {
      id: '/_public/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof PublicCoursesCourseIdRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authenticated/c/courses': {
      id: '/_authenticated/c/courses'
      path: '/c/courses'
      fullPath: '/c/courses'
      preLoaderRoute: typeof AuthenticatedCCoursesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/c/$courseId': {
      id: '/_authenticated/c/$courseId'
      path: '/c/$courseId'
      fullPath: '/c/$courseId'
      preLoaderRoute: typeof AuthenticatedCCourseIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_admin/a': {
      id: '/_authenticated/_admin/a'
      path: '/a'
      fullPath: '/a'
      preLoaderRoute: typeof AuthenticatedAdminARouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/c/$courseId/': {
      id: '/_authenticated/c/$courseId/'
      path: '/'
      fullPath: '/c/$courseId/'
      preLoaderRoute: typeof AuthenticatedCCourseIdIndexRouteImport
      parentRoute: typeof AuthenticatedCCourseIdRoute
    }
    '/_authenticated/_admin/a/': {
      id: '/_authenticated/_admin/a/'
      path: '/'
      fullPath: '/a/'
      preLoaderRoute: typeof AuthenticatedAdminAIndexRouteImport
      parentRoute: typeof AuthenticatedAdminARoute
    }
    '/_authenticated/_admin/a/users': {
      id: '/_authenticated/_admin/a/users'
      path: '/users'
      fullPath: '/a/users'
      preLoaderRoute: typeof AuthenticatedAdminAUsersRouteImport
      parentRoute: typeof AuthenticatedAdminARoute
    }
    '/_authenticated/_admin/a/courses': {
      id: '/_authenticated/_admin/a/courses'
      path: '/courses'
      fullPath: '/a/courses'
      preLoaderRoute: typeof AuthenticatedAdminACoursesRouteImport
      parentRoute: typeof AuthenticatedAdminARoute
    }
    '/_authenticated/_admin/a/content-approvals': {
      id: '/_authenticated/_admin/a/content-approvals'
      path: '/content-approvals'
      fullPath: '/a/content-approvals'
      preLoaderRoute: typeof AuthenticatedAdminAContentApprovalsRouteImport
      parentRoute: typeof AuthenticatedAdminARoute
    }
    '/_authenticated/_admin/a/users/': {
      id: '/_authenticated/_admin/a/users/'
      path: '/'
      fullPath: '/a/users/'
      preLoaderRoute: typeof AuthenticatedAdminAUsersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminAUsersRoute
    }
    '/_authenticated/_admin/a/courses/': {
      id: '/_authenticated/_admin/a/courses/'
      path: '/'
      fullPath: '/a/courses/'
      preLoaderRoute: typeof AuthenticatedAdminACoursesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminACoursesRoute
    }
    '/_authenticated/_admin/a/content/': {
      id: '/_authenticated/_admin/a/content/'
      path: '/content'
      fullPath: '/a/content'
      preLoaderRoute: typeof AuthenticatedAdminAContentIndexRouteImport
      parentRoute: typeof AuthenticatedAdminARoute
    }
    '/_authenticated/_admin/a/content-approvals/': {
      id: '/_authenticated/_admin/a/content-approvals/'
      path: '/'
      fullPath: '/a/content-approvals/'
      preLoaderRoute: typeof AuthenticatedAdminAContentApprovalsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminAContentApprovalsRoute
    }
    '/_authenticated/_admin/a/categories/': {
      id: '/_authenticated/_admin/a/categories/'
      path: '/categories'
      fullPath: '/a/categories'
      preLoaderRoute: typeof AuthenticatedAdminACategoriesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminARoute
    }
    '/_authenticated/_admin/a/analytics/': {
      id: '/_authenticated/_admin/a/analytics/'
      path: '/analytics'
      fullPath: '/a/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAAnalyticsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminARoute
    }
    '/_authenticated/_admin/a/users/create': {
      id: '/_authenticated/_admin/a/users/create'
      path: '/create'
      fullPath: '/a/users/create'
      preLoaderRoute: typeof AuthenticatedAdminAUsersCreateRouteImport
      parentRoute: typeof AuthenticatedAdminAUsersRoute
    }
    '/_authenticated/_admin/a/users/$userId': {
      id: '/_authenticated/_admin/a/users/$userId'
      path: '/$userId'
      fullPath: '/a/users/$userId'
      preLoaderRoute: typeof AuthenticatedAdminAUsersUserIdRouteImport
      parentRoute: typeof AuthenticatedAdminAUsersRoute
    }
    '/_authenticated/_admin/a/courses/new': {
      id: '/_authenticated/_admin/a/courses/new'
      path: '/new'
      fullPath: '/a/courses/new'
      preLoaderRoute: typeof AuthenticatedAdminACoursesNewRouteImport
      parentRoute: typeof AuthenticatedAdminACoursesRoute
    }
    '/_authenticated/_admin/a/courses/$courseId': {
      id: '/_authenticated/_admin/a/courses/$courseId'
      path: '/$courseId'
      fullPath: '/a/courses/$courseId'
      preLoaderRoute: typeof AuthenticatedAdminACoursesCourseIdRouteImport
      parentRoute: typeof AuthenticatedAdminACoursesRoute
    }
    '/_authenticated/_admin/a/categories/organize': {
      id: '/_authenticated/_admin/a/categories/organize'
      path: '/categories/organize'
      fullPath: '/a/categories/organize'
      preLoaderRoute: typeof AuthenticatedAdminACategoriesOrganizeRouteImport
      parentRoute: typeof AuthenticatedAdminARoute
    }
    '/_authenticated/_admin/a/categories/new': {
      id: '/_authenticated/_admin/a/categories/new'
      path: '/categories/new'
      fullPath: '/a/categories/new'
      preLoaderRoute: typeof AuthenticatedAdminACategoriesNewRouteImport
      parentRoute: typeof AuthenticatedAdminARoute
    }
    '/_authenticated/_admin/a/analytics/reports': {
      id: '/_authenticated/_admin/a/analytics/reports'
      path: '/analytics/reports'
      fullPath: '/a/analytics/reports'
      preLoaderRoute: typeof AuthenticatedAdminAAnalyticsReportsRouteImport
      parentRoute: typeof AuthenticatedAdminARoute
    }
    '/_authenticated/_admin/a/analytics/enrollments': {
      id: '/_authenticated/_admin/a/analytics/enrollments'
      path: '/analytics/enrollments'
      fullPath: '/a/analytics/enrollments'
      preLoaderRoute: typeof AuthenticatedAdminAAnalyticsEnrollmentsRouteImport
      parentRoute: typeof AuthenticatedAdminARoute
    }
    '/_authenticated/_admin/a/analytics/courses': {
      id: '/_authenticated/_admin/a/analytics/courses'
      path: '/analytics/courses'
      fullPath: '/a/analytics/courses'
      preLoaderRoute: typeof AuthenticatedAdminAAnalyticsCoursesRouteImport
      parentRoute: typeof AuthenticatedAdminARoute
    }
    '/_authenticated/c/$courseId/m/$moduleId/': {
      id: '/_authenticated/c/$courseId/m/$moduleId/'
      path: '/m/$moduleId'
      fullPath: '/c/$courseId/m/$moduleId'
      preLoaderRoute: typeof AuthenticatedCCourseIdMModuleIdIndexRouteImport
      parentRoute: typeof AuthenticatedCCourseIdRoute
    }
    '/_authenticated/_admin/a/content/$contentType/$contentId': {
      id: '/_authenticated/_admin/a/content/$contentType/$contentId'
      path: '/content/$contentType/$contentId'
      fullPath: '/a/content/$contentType/$contentId'
      preLoaderRoute: typeof AuthenticatedAdminAContentContentTypeContentIdRouteImport
      parentRoute: typeof AuthenticatedAdminARoute
    }
    '/_authenticated/c/$courseId/m/$moduleId/lessons/$lessonId': {
      id: '/_authenticated/c/$courseId/m/$moduleId/lessons/$lessonId'
      path: '/m/$moduleId/lessons/$lessonId'
      fullPath: '/c/$courseId/m/$moduleId/lessons/$lessonId'
      preLoaderRoute: typeof AuthenticatedCCourseIdMModuleIdLessonsLessonIdRouteImport
      parentRoute: typeof AuthenticatedCCourseIdRoute
    }
  }
}

interface AuthenticatedAdminAContentApprovalsRouteChildren {
  AuthenticatedAdminAContentApprovalsIndexRoute: typeof AuthenticatedAdminAContentApprovalsIndexRoute
}

const AuthenticatedAdminAContentApprovalsRouteChildren: AuthenticatedAdminAContentApprovalsRouteChildren =
  {
    AuthenticatedAdminAContentApprovalsIndexRoute:
      AuthenticatedAdminAContentApprovalsIndexRoute,
  }

const AuthenticatedAdminAContentApprovalsRouteWithChildren =
  AuthenticatedAdminAContentApprovalsRoute._addFileChildren(
    AuthenticatedAdminAContentApprovalsRouteChildren,
  )

interface AuthenticatedAdminACoursesRouteChildren {
  AuthenticatedAdminACoursesCourseIdRoute: typeof AuthenticatedAdminACoursesCourseIdRoute
  AuthenticatedAdminACoursesNewRoute: typeof AuthenticatedAdminACoursesNewRoute
  AuthenticatedAdminACoursesIndexRoute: typeof AuthenticatedAdminACoursesIndexRoute
}

const AuthenticatedAdminACoursesRouteChildren: AuthenticatedAdminACoursesRouteChildren =
  {
    AuthenticatedAdminACoursesCourseIdRoute:
      AuthenticatedAdminACoursesCourseIdRoute,
    AuthenticatedAdminACoursesNewRoute: AuthenticatedAdminACoursesNewRoute,
    AuthenticatedAdminACoursesIndexRoute: AuthenticatedAdminACoursesIndexRoute,
  }

const AuthenticatedAdminACoursesRouteWithChildren =
  AuthenticatedAdminACoursesRoute._addFileChildren(
    AuthenticatedAdminACoursesRouteChildren,
  )

interface AuthenticatedAdminAUsersRouteChildren {
  AuthenticatedAdminAUsersUserIdRoute: typeof AuthenticatedAdminAUsersUserIdRoute
  AuthenticatedAdminAUsersCreateRoute: typeof AuthenticatedAdminAUsersCreateRoute
  AuthenticatedAdminAUsersIndexRoute: typeof AuthenticatedAdminAUsersIndexRoute
}

const AuthenticatedAdminAUsersRouteChildren: AuthenticatedAdminAUsersRouteChildren =
  {
    AuthenticatedAdminAUsersUserIdRoute: AuthenticatedAdminAUsersUserIdRoute,
    AuthenticatedAdminAUsersCreateRoute: AuthenticatedAdminAUsersCreateRoute,
    AuthenticatedAdminAUsersIndexRoute: AuthenticatedAdminAUsersIndexRoute,
  }

const AuthenticatedAdminAUsersRouteWithChildren =
  AuthenticatedAdminAUsersRoute._addFileChildren(
    AuthenticatedAdminAUsersRouteChildren,
  )

interface AuthenticatedAdminARouteChildren {
  AuthenticatedAdminAContentApprovalsRoute: typeof AuthenticatedAdminAContentApprovalsRouteWithChildren
  AuthenticatedAdminACoursesRoute: typeof AuthenticatedAdminACoursesRouteWithChildren
  AuthenticatedAdminAUsersRoute: typeof AuthenticatedAdminAUsersRouteWithChildren
  AuthenticatedAdminAIndexRoute: typeof AuthenticatedAdminAIndexRoute
  AuthenticatedAdminAAnalyticsCoursesRoute: typeof AuthenticatedAdminAAnalyticsCoursesRoute
  AuthenticatedAdminAAnalyticsEnrollmentsRoute: typeof AuthenticatedAdminAAnalyticsEnrollmentsRoute
  AuthenticatedAdminAAnalyticsReportsRoute: typeof AuthenticatedAdminAAnalyticsReportsRoute
  AuthenticatedAdminACategoriesNewRoute: typeof AuthenticatedAdminACategoriesNewRoute
  AuthenticatedAdminACategoriesOrganizeRoute: typeof AuthenticatedAdminACategoriesOrganizeRoute
  AuthenticatedAdminAAnalyticsIndexRoute: typeof AuthenticatedAdminAAnalyticsIndexRoute
  AuthenticatedAdminACategoriesIndexRoute: typeof AuthenticatedAdminACategoriesIndexRoute
  AuthenticatedAdminAContentIndexRoute: typeof AuthenticatedAdminAContentIndexRoute
  AuthenticatedAdminAContentContentTypeContentIdRoute: typeof AuthenticatedAdminAContentContentTypeContentIdRoute
}

const AuthenticatedAdminARouteChildren: AuthenticatedAdminARouteChildren = {
  AuthenticatedAdminAContentApprovalsRoute:
    AuthenticatedAdminAContentApprovalsRouteWithChildren,
  AuthenticatedAdminACoursesRoute: AuthenticatedAdminACoursesRouteWithChildren,
  AuthenticatedAdminAUsersRoute: AuthenticatedAdminAUsersRouteWithChildren,
  AuthenticatedAdminAIndexRoute: AuthenticatedAdminAIndexRoute,
  AuthenticatedAdminAAnalyticsCoursesRoute:
    AuthenticatedAdminAAnalyticsCoursesRoute,
  AuthenticatedAdminAAnalyticsEnrollmentsRoute:
    AuthenticatedAdminAAnalyticsEnrollmentsRoute,
  AuthenticatedAdminAAnalyticsReportsRoute:
    AuthenticatedAdminAAnalyticsReportsRoute,
  AuthenticatedAdminACategoriesNewRoute: AuthenticatedAdminACategoriesNewRoute,
  AuthenticatedAdminACategoriesOrganizeRoute:
    AuthenticatedAdminACategoriesOrganizeRoute,
  AuthenticatedAdminAAnalyticsIndexRoute:
    AuthenticatedAdminAAnalyticsIndexRoute,
  AuthenticatedAdminACategoriesIndexRoute:
    AuthenticatedAdminACategoriesIndexRoute,
  AuthenticatedAdminAContentIndexRoute: AuthenticatedAdminAContentIndexRoute,
  AuthenticatedAdminAContentContentTypeContentIdRoute:
    AuthenticatedAdminAContentContentTypeContentIdRoute,
}

const AuthenticatedAdminARouteWithChildren =
  AuthenticatedAdminARoute._addFileChildren(AuthenticatedAdminARouteChildren)

interface AuthenticatedCCourseIdRouteChildren {
  AuthenticatedCCourseIdIndexRoute: typeof AuthenticatedCCourseIdIndexRoute
  AuthenticatedCCourseIdMModuleIdIndexRoute: typeof AuthenticatedCCourseIdMModuleIdIndexRoute
  AuthenticatedCCourseIdMModuleIdLessonsLessonIdRoute: typeof AuthenticatedCCourseIdMModuleIdLessonsLessonIdRoute
}

const AuthenticatedCCourseIdRouteChildren: AuthenticatedCCourseIdRouteChildren =
  {
    AuthenticatedCCourseIdIndexRoute: AuthenticatedCCourseIdIndexRoute,
    AuthenticatedCCourseIdMModuleIdIndexRoute:
      AuthenticatedCCourseIdMModuleIdIndexRoute,
    AuthenticatedCCourseIdMModuleIdLessonsLessonIdRoute:
      AuthenticatedCCourseIdMModuleIdLessonsLessonIdRoute,
  }

const AuthenticatedCCourseIdRouteWithChildren =
  AuthenticatedCCourseIdRoute._addFileChildren(
    AuthenticatedCCourseIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminARoute: typeof AuthenticatedAdminARouteWithChildren
  AuthenticatedCCourseIdRoute: typeof AuthenticatedCCourseIdRouteWithChildren
  AuthenticatedCCoursesRoute: typeof AuthenticatedCCoursesRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminARoute: AuthenticatedAdminARouteWithChildren,
  AuthenticatedCCourseIdRoute: AuthenticatedCCourseIdRouteWithChildren,
  AuthenticatedCCoursesRoute: AuthenticatedCCoursesRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicContactRoute: typeof PublicContactRoute
  PublicFaqRoute: typeof PublicFaqRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicCoursesCourseIdRoute: typeof PublicCoursesCourseIdRoute
  PublicStaffLoginRoute: typeof PublicStaffLoginRoute
  PublicCoursesIndexRoute: typeof PublicCoursesIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicContactRoute: PublicContactRoute,
  PublicFaqRoute: PublicFaqRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicCoursesCourseIdRoute: PublicCoursesCourseIdRoute,
  PublicStaffLoginRoute: PublicStaffLoginRoute,
  PublicCoursesIndexRoute: PublicCoursesIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
